const ActionTypes = {
  TASKS: {
    FETCH: 'FETCH TASKS',
    FETCH_FINISHED: 'FETCH TASKS FINISHED',
  },
  TASK_INSTANCE: {
    //OPEN: 'OPEN TASK INSTANCE',
    CREATE: 'CREATE TASK INSTANCE',
    CHANGE_CODE: 'CHANGE CODE IN TASK INSTANCE"
    RUN: 'RUN TASK INSTANCE',
    EXECUTE_COMMAND: 'EXECUTE COMMAND IN TASK INSTANCE',
    RESET: 'RESET TASK INSTANCE',
    LOAD_SOLUTION: 'LOAD SOLUTION OF TASK INSTANCE',
    EXPORT_CODE: 'EXPORT CODE OF TASK INSTANCE',
  }
};

export default ActionTypes;
